export const dicionario = [

    { palavra: 'amor', definicao: 'Sentimento de profunda afeição por alguém ou algo.' },
    { palavra: 'paz', definicao: 'Estado de calma, tranquilidade e ausência de conflitos.' },
    { palavra: 'esperança', definicao: 'Sentimento de que algo bom irá acontecer; confiança no futuro.' },
    { palavra: 'liberdade', definicao: 'Capacidade de agir sem restrições ou opressão.' },
    { palavra: 'sabedoria', definicao: 'Conhecimento profundo e discernimento.' },
    { palavra: 'felicidade', definicao: 'Estado de contentamento e alegria.' },
    { palavra: 'viagem', definicao: 'Ato de viajar; percurso feito de um lugar para outro.' },
    { palavra: 'conhecimento', definicao: 'Ato ou efeito de conhecer; saber adquirido.' },
    { palavra: 'natureza', definicao: 'O conjunto de tudo que existe no universo, exceto o que é produzido pelo homem.' },
    { palavra: 'cultura', definicao: 'Conjunto de costumes e valores de um povo.' },
    { palavra: 'desafio', definicao: 'Obstáculo ou dificuldade que exige esforço para ser superado.' },
    { palavra: 'inovação', definicao: 'Ato ou efeito de inovar; introdução de novidades.' },
    { palavra: 'curiosidade', definicao: 'Desejo de conhecer, explorar ou aprender.' },
    { palavra: 'criatividade', definicao: 'Capacidade de criar, inventar, inovar.' },
    { palavra: 'alegria', definicao: 'Sentimento de grande contentamento; júbilo.' },
    { palavra: 'empatia', definicao: 'Capacidade de se colocar no lugar de outra pessoa, compreendendo seus sentimentos e perspectivas.' },
    { palavra: 'resiliência', definicao: 'Capacidade de se recuperar de situações difíceis e se adaptar a mudanças.' },
    { palavra: 'persistência', definicao: 'Qualidade de quem não desiste facilmente, continuando a fazer algo apesar das dificuldades.' },
    { palavra: 'gratidão', definicao: 'Sentimento de reconhecimento e apreço por um benefício recebido.' },
    { palavra: 'harmonia', definicao: 'Acordo, conformidade ou concórdia; relação de sons agradáveis.' },
    { palavra: 'inteligência', definicao: 'Capacidade de aprender, entender e aplicar conhecimentos.' },
    { palavra: 'progresso', definicao: 'Desenvolvimento ou avanço em direção a um objetivo.' },
    { palavra: 'sonho', definicao: 'Experiência imaginativa durante o sono; aspiração ou desejo.' },
    { palavra: 'memória', definicao: 'Capacidade de reter e recordar informações, experiências e conhecimentos.' },
    { palavra: 'reflexão', definicao: 'Ato de pensar profundamente sobre algo; meditação.' },
    { palavra: 'saúde', definicao: 'Estado de bem-estar físico, mental e social completo.' },
    { palavra: 'otimismo', definicao: 'Tendência a ver o lado positivo das coisas; esperança.' },
    { palavra: 'amizade', definicao: 'Sentimento de afeição, estima e lealdade entre pessoas.' },
    { palavra: 'família', definicao: 'Grupo de pessoas unidas por laços de parentesco, casamento ou adoção.' },
    { palavra: 'trabalho', definicao: 'Atividade física ou mental realizada para produzir algo ou atingir um objetivo.' },
    { palavra: 'justiça', definicao: 'Princípio de equidade e imparcialidade; virtude de dar a cada um o que lhe é devido.' },
    { palavra: 'honra', definicao: 'Qualidade de quem age com retidão e dignidade; reputação ilibada.' },
    { palavra: 'respeito', definicao: 'Ato de considerar os direitos e a dignidade de outra pessoa; reverência.' },
    { palavra: 'verdade', definicao: 'Conformidade com os fatos ou com a realidade; autenticidade.' },
    { palavra: 'disciplina', definicao: 'Obediência a regras ou normas; rigor no cumprimento de deveres.' },
    { palavra: 'coragem', definicao: 'Qualidade de quem enfrenta o perigo ou o medo; bravura.' },
    { palavra: 'gentileza', definicao: 'Qualidade de quem é gentil; delicadeza e amabilidade.' },
    { palavra: 'gratidão', definicao: 'Sentimento de reconhecimento por um benefício recebido.' },
    { palavra: 'humildade', definicao: 'Qualidade de quem reconhece suas próprias limitações; modéstia.' },
    { palavra: 'paciência', definicao: 'Virtude de suportar contratempos sem perder a calma.' },
    { palavra: 'altruísmo', definicao: 'Atitude de se preocupar com o bem-estar alheio; abnegação.' },
    { palavra: 'generosidade', definicao: 'Qualidade de quem é generoso; disposição para dar e ajudar.' },
    { palavra: 'compreensão', definicao: 'Capacidade de entender; ato de compreender.' },
    { palavra: 'tolerância', definicao: 'Capacidade de aceitar e respeitar as diferenças.' },
    { palavra: 'integridade', definicao: 'Qualidade de quem é íntegro; retidão moral.' },
    { palavra: 'lealdade', definicao: 'Qualidade de quem é fiel e dedicado.' },
    { palavra: 'responsabilidade', definicao: 'Dever de responder por seus atos; obrigação.' },
    { palavra: 'perseverança', definicao: 'Qualidade de quem persevera; firmeza em um propósito.' },
    { palavra: 'criatividade', definicao: 'Capacidade de criar e inovar.' },
    { palavra: 'aprendizado', definicao: 'Ato de adquirir conhecimento ou habilidade.' },
    { palavra: 'desenvolvimento', definicao: 'Processo de crescimento e aprimoramento.' },
    { palavra: 'equilíbrio', definicao: 'Estado de estabilidade e harmonia.' },
    { palavra: 'espírito', definicao: 'Parte imaterial do ser humano; ânimo, vivacidade.' },
    { palavra: 'excelência', definicao: 'Qualidade do que é superior, que se destaca.' },
];