export const dicionario = [
    { palavra: 'abundância', definicao: 'Grande quantidade; fartura.' },
    { palavra: 'aceleração', definicao: 'Ato ou efeito de acelerar; aumento da velocidade.' },
    { palavra: 'adaptabilidade', definicao: 'Capacidade de se ajustar a novas condições.' },
    { palavra: 'afeto', definicao: 'Disposição de alguém por alguma coisa, seja positiva ou negativa. É a partir do afeto construído que se demonstram emoções ou sentimentos.' },
    { palavra: 'alegria', definicao: 'Sentimento de grande contentamento; júbilo.' },
    { palavra: 'altruísmo', definicao: 'Atitude de se preocupar com o bem-estar alheio; abnegação.' },
    { palavra: 'amizade', definicao: 'Sentimento de afeição, estima e lealdade entre pessoas.' },
    { palavra: 'amor', definicao: 'Sentimento de profunda afeição por alguém ou algo.' },
    { palavra: 'anarquia', definicao: 'Ausência de governo ou autoridade; desordem.' },
    { palavra: 'angústia', definicao: 'Sentimento que se liga a uma sensação interna de opressão ou de desespero; grande aflição do espírito, tormento, tortura.' },
    { palavra: 'aprendizado', definicao: 'Ato de adquirir conhecimento ou habilidade.' },
    { palavra: 'autenticidade', definicao: 'Qualidade do que é autêntico; verdadeiro, genuíno.' },
    { palavra: 'autoconfiança', definicao: 'Confiança em suas próprias capacidades e julgamento.' },
    { palavra: 'beleza', definicao: 'Qualidade que agrada os sentidos ou o espírito.' },
    { palavra: 'calma', definicao: 'Estado de tranquilidade, ausência de agitação.' },
    { palavra: 'camaradagem', definicao: 'Espírito de amizade e solidariedade entre camaradas.' },
    { palavra: 'carinho', definicao: 'Demonstração de afeto, ternura.' },
    { palavra: 'colaboração', definicao: 'Ato de trabalhar em conjunto para um fim comum.' },
    { palavra: 'comprometimento', definicao: 'Ato ou efeito de comprometer-se. Promessa recíproca de alguém que tende a cumprir com os seus acordos, independentemente da forma que eles sejam feitos.' },
    { palavra: 'compaixão', definicao: 'Sentimento de pena e ternura para com o sofrimento alheio.' },
    { palavra: 'compreensão', definicao: 'Capacidade de entender; ato de compreender.' },
    { palavra: 'comunidade', definicao: 'Grupo de indivíduos que vivem juntos ou compartilham interesses comuns.' },
    { palavra: 'conexão', definicao: 'Ato ou efeito de conectar, de ligar ou de unir; ligação, união.' },
    { palavra: 'conhecimento', definicao: 'Ato ou efeito de conhecer; saber adquirido.' },
    { palavra: 'consideração', definicao: 'Ato ou efeito de considerar; exame minucioso, refletido, apreciação.' },
    { palavra: 'contentamento', definicao: 'Estado de satisfação e alegria.' },
    { palavra: 'contemplação', definicao: 'Ato de observar com atenção e reflexão.' },
    { palavra: 'coragem', definicao: 'Qualidade de quem enfrenta o perigo ou o medo; bravura.' },
    { palavra: 'cortesia', definicao: 'Qualidade de ser cortês; educação, gentileza.' },
    { palavra: 'covardia', definicao: 'Comportamento que revela fraqueza de espírito, falta de coragem e medo.' },
    { palavra: 'criatividade', definicao: 'Capacidade de criar, inventar, inovar.' },
    { palavra: 'cultura', definicao: 'Conjunto de costumes e valores de um povo.' },
    { palavra: 'curiosidade', definicao: 'Desejo de conhecer, explorar ou aprender.' },
    { palavra: 'dedicação', definicao: 'Ato de dedicar-se; entrega total a uma causa ou pessoa.' },
    { palavra: 'desafio', definicao: 'Obstáculo ou dificuldade que exige esforço para ser superado.' },
    { palavra: 'descoberta', definicao: 'Ato ou efeito de descobrir algo novo.' },
    { palavra: 'desenvolvimento', definicao: 'Processo de crescimento e aprimoramento.' },
    { palavra: 'determinação', definicao: 'Firmeza de propósito; persistência.' },
    { palavra: 'dignidade', definicao: 'Qualidade de ser digno; respeito por si mesmo e pelos outros.' },
    { palavra: 'disciplina', definicao: 'Obediência a regras ou normas; rigor no cumprimento de deveres.' },
    { palavra: 'diversidade', definicao: 'Variedade; pluralidade de elementos.' },
    { palavra: 'empatia', definicao: 'Capacidade de se imaginar no lugar de outra pessoa.' },
    { palavra: 'entendimento', definicao: 'Ação ou efeito de entender. Capacidade de entender e julgar os seres e as coisas.' },
    { palavra: 'entusiasmo', definicao: 'Grande exaltação de ânimo; fervor.' },
    { palavra: 'equilíbrio', definicao: 'Estado de estabilidade e harmonia.' },
    { palavra: 'esperança', definicao: 'Sentimento de que algo bom irá acontecer; confiança no futuro.' },
    { palavra: 'espírito', definicao: 'Parte imaterial do ser humano; ânimo, vivacidade.' },
    { palavra: 'estímulo', definicao: 'Aquilo que incita ou impulsiona a ação.' },
    { palavra: 'excelência', definicao: 'Qualidade do que é superior, que se destaca.' },
    { palavra: 'família', definicao: 'Grupo de pessoas unidas por laços de parentesco, casamento ou adoção.' },
    { palavra: 'felicidade', definicao: 'Estado de contentamento e alegria.' },
    { palavra: 'fidelidade', definicao: 'Atributo ou a qualidade de quem ou do que é fiel.' },
    { palavra: 'flexibilidade', definicao: 'Capacidade de se adaptar a diferentes situações ou exigências.' },
    { palavra: 'generosidade', definicao: 'Qualidade de quem é generoso; disposição para dar e ajudar.' },
    { palavra: 'gentileza', definicao: 'Qualidade de quem é gentil; delicadeza e amabilidade.' },
    { palavra: 'gratidão', definicao: 'Sentimento de reconhecimento e apreço por um benefício recebido.' },
    { palavra: 'harmonia', definicao: 'Acordo, conformidade ou concórdia; relação de sons agradáveis.' },
    { palavra: 'honestidade', definicao: 'Qualidade do que age com retidão, de acordo com a verdade, seriedade, probidade.' },
    { palavra: 'honra', definicao: 'Qualidade de quem age com retidão e dignidade; reputação ilibada.' },
    { palavra: 'humildade', definicao: 'Qualidade de quem reconhece suas próprias limitações; modéstia.' },
    { palavra: 'identidade', definicao: 'Conjunto de características que distinguem uma pessoa ou coisa.' },
    { palavra: 'iluminação', definicao: 'Ato ou efeito de iluminar; clareza, compreensão espiritual.' },
    { palavra: 'imaginação', definicao: 'Capacidade de criar imagens ou ideias na mente.' },
    { palavra: 'inspiração', definicao: 'Estímulo criativo; sopro divino.' },
    { palavra: 'integridade', definicao: 'Qualidade de quem é íntegro; retidão moral.' },
    { palavra: 'inteligência', definicao: 'Capacidade de aprender, entender e aplicar conhecimentos.' },
    { palavra: 'intuição', definicao: 'Ato ou faculdade de perceber algo sem raciocínio ou análise.' },
    { palavra: 'inovação', definicao: 'Ato ou efeito de inovar; introdução de novidades.' },
    { palavra: 'justiça', definicao: 'Princípio de equidade e imparcialidade; virtude de dar a cada um o que lhe é devido.' },
    { palavra: 'lealdade', definicao: 'Qualidade de quem é fiel e dedicado.' },
    { palavra: 'legado', definicao: 'Aquilo que se transmite às gerações futuras; herança.' },
    { palavra: 'leveza', definicao: 'Qualidade do que é leve; ausência de peso, agilidade.' },
    { palavra: 'liberdade', definicao: 'Capacidade de agir sem restrições ou opressão.' },
    { palavra: 'liderança', definicao: 'Ato de conduzir; capacidade de chefiar, de guiar.' },
    { palavra: 'luminosidade', definicao: 'Qualidade do que emite ou reflete luz; brilho.' },
    { palavra: 'maturidade', definicao: 'Estado ou condição de ter atingido uma forma adulta ou amadurecida.' },
    { palavra: 'memória', definicao: 'Capacidade de reter e recordar informações, experiências e conhecimentos.' },
    { palavra: 'motivação', definicao: 'Razão ou motivo que leva alguém a agir.' },
    { palavra: 'natureza', definicao: 'O conjunto de tudo que existe no universo, exceto o que é produzido pelo homem.' },
    { palavra: 'otimismo', definicao: 'Tendência a ver o lado positivo das coisas; esperança.' },
    { palavra: 'paciência', definicao: 'Virtude de suportar contratempos sem perder a calma.' },
    { palavra: 'paixão', definicao: 'Sentimento forte e intenso de amor, afeição ou entusiasmo.' },
    { palavra: 'paz', definicao: 'Estado de calma, tranquilidade e ausência de conflitos.' },
    { palavra: 'percepção', definicao: 'Capacidade de adquirir conhecimento através dos sentidos.' },
    { palavra: 'perseverança', definicao: 'Qualidade de quem persevera; firmeza em um propósito.' },
    { palavra: 'persistência', definicao: 'Qualidade de quem não desiste facilmente, continuando a fazer algo apesar das dificuldades.' },
    { palavra: 'plenitude', definicao: 'Estado de estar completo, cheio, perfeito.' },
    { palavra: 'ponderação', definicao: 'Ato de ponderar; reflexão cuidadosa, prudência.' },
    { palavra: 'progresso', definicao: 'Desenvolvimento ou avanço em direção a um objetivo.' },
    { palavra: 'propósito', definicao: 'Intenção; objetivo a ser alcançado.' },
    { palavra: 'qualidade', definicao: 'Caráter do que é bom ou excelente.' },
    { palavra: 'realização', definicao: 'Ato de realizar; concretização de um desejo ou projeto.' },
    { palavra: 'reflexão', definicao: 'Ato de pensar profundamente sobre algo; meditação.' },
    { palavra: 'relacionamento', definicao: 'Ligação afetiva, profissional ou de amizade entre pessoas que se unem com os mesmos objetivos e interesses.' },
    { palavra: 'resiliência', definicao: 'Capacidade de se recuperar de situações difíceis e se adaptar a mudanças.' },
    { palavra: 'respeito', definicao: 'Ato de considerar os direitos e a dignidade de outra pessoa; reverência.' },
    { palavra: 'responsabilidade', definicao: 'Qualidade de quem é responsável. Obrigatoriedade de responder pelos próprios atos ou por aqueles praticados por algum subordinado.' },
    { palavra: 'sabedoria', definicao: 'Conhecimento profundo e discernimento.' },
    { palavra: 'saúde', definicao: 'Estado de bem-estar físico, mental e social completo.' },
    { palavra: 'serenidade', definicao: 'Estado de ser sereno; calma, tranquilidade de espírito.' },
    { palavra: 'sonho', definicao: 'Experiência imaginativa durante o sono; aspiração ou desejo.' },
    { palavra: 'superação', definicao: 'Ato ou efeito de superar; vencer um obstáculo.' },
    { palavra: 'sustentabilidade', definicao: 'Capacidade de suprir as necessidades do presente sem comprometer as futuras.' },
    { palavra: 'talento', definicao: 'Habilidade ou aptidão natural para algo.' },
    { palavra: 'tolerância', definicao: 'Capacidade de aceitar e respeitar as diferenças.' },
    { palavra: 'trabalho', definicao: 'Atividade física ou mental realizada para produzir algo ou atingir um objetivo.' },
    { palavra: 'união', definicao: 'Ato de unir ou ligar; junção, coesão.' },
    { palavra: 'verdade', definicao: 'Conformidade com os fatos ou com a realidade; autenticidade.' },
    { palavra: 'viagem', definicao: 'Ato de viajar; percurso feito de um lugar para outro.' },
    { palavra: 'vitalidade', definicao: 'Qualidade do que possui vida; energia, vigor.' },
    { palavra: 'vulnerabilidade', definicao: 'Qualidade do que é vulnerável; suscetibilidade a ser ferido ou afetado.' },
    { palavra: 'zelo', definicao: 'Cuidado atento e diligente; dedicação intensa.' },
];